version: '3.8'

services:
  mysql:
    image: mysql:8
    ports:
      - published: $MYSQL_PORT
        target: 3306
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 1s
      timeout: 3s
      retries: 30
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
