version: '3.8'

services:
  mysql:
    image: mysql:8
    ports:
      - published: $TEST_MYSQL_PORT
        target: 3306
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 1s
      timeout: 3s
      retries: 30
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: $TEST_MYSQL_DATABASE
