version: '3.8'

services:
  mysql:
    image: mysql:8@sha256:d45561a65aba6edac77be36e0a53f0c1fba67b951cb728348522b671ad63f926
    ports:
      - published: $TEST_MYSQL_PORT
        target: 3306
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 1s
      timeout: 3s
      retries: 30
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: $TEST_MYSQL_DATABASE
