name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  protolint:
    name: protolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: plexsystems/protolint-action@v0.2.0

  cspell:
    name: cspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: streetsidesoftware/cspell-action@v1.0.1
