name: Validate Renovate

on:
  pull_request:
    paths:
      - .renovaterc.json
      - .github/workflows/validate-renovate.yml

jobs:
  validate-renovate:
    name: renovate-config-validator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          npx --package renovate -c renovate-config-validator
